<?
$conf['pointsWinCup_1'] = "550";//ilosc punktow w pucharze dnia za miejsce 1
$conf['pointsWinCup_2'] = "350";//ilosc punktow w pucharze dnia za miejsce 2
$conf['pointsWinCup_3'] = "250";//ilosc punktow w pucharze dnia za miejsce 3
$conf['dayRank_1'] = "250";//ilosc punktow za miejsce 1 w rankingu dnia
$conf['dayRank_2'] = "200";//ilosc punktow za miejsce 2 w rankingu dnia
$conf['dayRank_3'] = "150";//ilosc punktow za miejsce 3 w rankingu dnia
$conf['monthsRank_1'] = "450";//ilosc punktow za miejsce 1 w rankingu miesiaca
$conf['monthsRank_2'] = "400";//ilosc punktow za miejsce 2 w rankingu miesiaca
$conf['monthsRank_3'] = "222";//ilosc punktow za miejsce 3 w rankingu miesiaca
$conf['weekRank_1'] = "350";//ilosc punktow za miejsce 1 w rankingu tygodnia
$conf['weekRank_2'] = "300";//ilosc punktow za miejsce 2 w rankingu tygodnia
$conf['weekRank_3'] = "250";//ilosc punktow za miejsce 3 w rankingu tygodnia
$conf['showLimitGuestOnline'] = "20";//ilosc pokazywanych gosci na stronie
$conf['showLimitUserOnline'] = "15";//ilosc pokazywanych userow na stronie
$conf['onlineUpdateTime'] = "600";//czas aktualizacji osob online
$conf['pointsWin'] = "120";//podstawa punktow za wygrane wyzwanie
$conf['pointsNoWiner'] = "40";//podstawa punktow za zremisowane wyzwanie
$conf['pointsLeagueWin'] = "300";//punkty za wygrany mecz ligowy
$conf['pointsLeagueNoWiner'] = "150";//punkty za remist w lidze
$conf['pointsTournamentWin'] = "1000";//punkty za wygrany mecz turniejowy
$conf['pointsTournamentNoWiner'] = "1000";//punkty za remis w turnieju
$conf['pointsSessionMatchMinus'] = "250";//minusowe punkty za ocene hostu
$conf['pointsSessionMatchPlus'] = "250";//plusowe punkty za ocene hostu
$conf['counterSessionMatch'] = "10";//limit sesji(co ile meczy sa wystawiane pkt)
$conf['pokerRankingGetPoints'] = "500";//ile punktow pobieranych jest do PokerRanku
$conf['pokerRankingPoul'] = "700";//ile punktow trafia do puli w PokerRanku
$conf['percentPokerRankWin_1'] = "50";//ile procent z puli dostaje osoba na 1 miejscu
$conf['percentPokerRankWin_2'] = "30";//ile procent z puli dostaje osoba na 2 miejscu
$conf['percentPokerRankWin_3'] = "20";//ile procent z puli dostaje osoba na 3 miejscu
$conf['limitRankSite'] = "10";//limit wyswietlanych na stronie osob w rankingu glownym
$conf['limitAddedPointsSite'] = "10";//limit wyswietlanych punktow dodatkowych
$conf['limitMaxResult'] = "20";//maxymalny wynik, ktory mozna wpisac w meczu
$conf['defaultGame'] = "pes4";//domyslna gra dla userow niezalogowanych(skrot)
$conf['botNo'] = "4682385";//numer bota gg (haslo w pliku z ustawieniami)
$conf['botDescription'] = "www.pesarena.pl - Najlepsza Liga Pro Evolution Soccer w sieci! Sprawdz SAM!";//opis bota GG
$conf['showDevil'] = "1";//wyswietlanie maskotki w panelu admina
$conf['adminTitleSite'] = "Zaawansowany Panel Administracyjny :: PESARENA.pl";//nazwa panelu admina
$conf['showMenuDescription'] = "1";//pokazuj chmurki z podpowiedziami w menu
$conf['ShowHelpMenu'] = "1";//pokazuj pomocne menu na dole PA
$conf['pointsWoLeague3_0'] = "100";//punkty za wo 3-0 w lidze
$conf['pointsWoLeague0_3'] = "-400";//punkty za wo 0-3 w lidze
$conf['pointsWoLeague0_0'] = "-400";//punkty za wo 0-0 w lidze
$conf['pointsMatchLeagueExWin'] = "500";//punkty za wygrana w extraklasie
$conf['pointsMatchLeagueExLos'] = "-100";//punkty za przegrana w extraklasie
$conf['pointsMatchLeagueExNoW'] = "170";//punkty za remis w extraklasie
$conf['pointsMatchLeague1Win'] = "400";//punkty za wygrana w 1 lidze
$conf['pointsMatchLeague1Los'] = "-130";//punkty za przegrana w 1 lidze
$conf['pointsMatchLeague1NoW'] = "140";//punkty za remis w 1 lidze
$conf['pointsMatchLeague2Win'] = "350";//punkty za wygrana w 2 lidze
$conf['pointsMatchLeague2Los'] = "-160";//punkty za przegrana w 2 lidze
$conf['pointsMatchLeague2NoW'] = "110";//punkty za remis w 2 lidze
$conf['pointsMatchLeague3Win'] = "300";//punkty za wygrana w 3 lidze
$conf['pointsMatchLeague3Los'] = "-190";//punkty za przegrana w 3 lidze
$conf['pointsMatchLeague3NoW'] = "80";//punkty za remis w 3 lidze
$conf['pointsMatchLeagueGrWin'] = "350";//punkty za wygrana w grupach w lidze
$conf['pointsMatchLeagueGrLos'] = "-75";//punkty za przegrana w grupach w lidze
$conf['pointsMatchLeagueGrNoW'] = "175";//punkty za remis w grupach w lidze
$conf['pointsWoTurniej3_0'] = "250";//punkty za wo 3-0 w turnieju
$conf['pointsWoTurniej0_3'] = "-200";//punkty za wo 0-3 w turnieju
$conf['pointsWoTurniej0_0'] = "-100";//punkty za wo 0-0 w turnieju
$conf['pointsWoCup3_0'] = "-200";//punkty za wo 3-0 w pucharze
$conf['pointsWoCup0_3'] = "100";//punkty za wo 0-3 w pucharze
$conf['minUsersToTournament'] = "16";//minimalna liczba graczy jaka musi byc do turnieju
?>